// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv"
import { defineConfig } from "prisma/config"

// Match Next.js: base `.env`, then `.env.local` overrides (so local dev isn’t stuck on `.env` only).
loadEnv({ path: ".env" })
loadEnv({ path: ".env.local", override: true })

/**
 * URL used by Prisma CLI only (`migrate`, `db push`, `introspect`).
 *
 * Supabase: `db.*.supabase.co:5432` often returns P1001 from local networks (IPv6, firewall).
 * Fix: set `MIGRATE_DATABASE_URL` to the **Session mode** URI from the dashboard
 * (Settings → Database → Connection string → Session pooler), or set
 * `PRISMA_CLI_USE_DATABASE_URL=1` to use the pooled `DATABASE_URL` (6543) for CLI — works for many setups;
 * if migrate errors on the pooler, use Session mode instead.
 *
 * Runtime PrismaClient still uses `process.env.DATABASE_URL` in `src/lib/prisma.ts`.
 */
function isValidPostgresUrl(url: string | undefined): url is string {
  if (!url) return false
  const trimmed = url.trim()
  if (!trimmed || trimmed.includes("<paste")) return false
  return trimmed.startsWith("postgresql://") || trimmed.startsWith("postgres://")
}

function resolveDatasourceUrl(): string | undefined {
  const migrateExplicit = process.env.MIGRATE_DATABASE_URL?.trim()
  if (isValidPostgresUrl(migrateExplicit)) return migrateExplicit

  const pooled = process.env.DATABASE_URL?.trim()
  const direct = process.env.DIRECT_URL?.trim()

  const usePooledForCli = ["1", "true", "yes"].includes(
    (process.env.PRISMA_CLI_USE_DATABASE_URL ?? "").trim().toLowerCase()
  )
  if (usePooledForCli && isValidPostgresUrl(pooled)) return pooled

  if (isValidPostgresUrl(direct)) return direct
  if (isValidPostgresUrl(pooled)) return pooled

  return undefined
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatasourceUrl(),
  },
})
